server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: demo-service
          uri: http://localhost:9090
          predicates:
            - Path=/demo/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: department-service
          uri: http://localhost:8082
          predicates:
            - Path=/department/**
