server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: demo-service
          uri: http://localhost:9090
          predicates:
            - Path=/demo/**
